TTL-delete mode
Eveneum/Eveneum pull request #35
Opened 2022-10-11 12:02 UTC by AriKuorikoski

TTL delete mode is sort of mix between hard and delete delete modes. When a stream is labeled as deleted, the document is given TTL, which presents the time to live in seconds after Cosmos DB will dispose the documents.  

TTL delete mode is set up in code, so that the DeleteMode on EventStoreOptions is set to TtlDelete and StreamTimeToLiveSecondsAfterDelete is set to expected TTL value. Default value for now is 24 hours. 

To be able to use this mode, the Cosmos DB collection needs to be set up, so that the default default Time to live is set to "on (no default)"

![image](https://user-images.githubusercontent.com/56065098/195083867-18464f52-df8f-42d5-8ed4-356c60be3b10.png)

2022-10-11 18:01 UTC, jkonecki commented
Thank you very much for a high-quality pull request. I appreciate you've added unit tests as well. 
I've added two tiny comments, once they are resolved I'll publish new NuGet packages

2022-10-12 08:00 UTC, AriKuorikoski commented
I added a few more tests in there. 

@jkonecki I did not see the comments, is there something I should do before you release the nugets?

2022-10-14 19:01 UTC, jkonecki requested changes

2022-10-17 06:01 UTC, AriKuorikoski commented on Eveneum/EventStoreOptions.cs
> +        public TimeSpan StreamTimeToLiveSecondsAfterDelete { get; set; } = TimeSpan.FromHours(24);
Implemented requested changes on the commit https://github.com/Eveneum/Eveneum/pull/35/commits/e2ff82ca664a68b41159b344321879858f553d16

2022-10-18 15:53 UTC, merged

2022-10-18 16:18 UTC, jkonecki commented
NuGet package is available now:
https://www.nuget.org/packages/Eveneum/6.3.0